flutter pub run pigeon \
  --input pigeons/message.dart \
  --dart_out lib/pigeon.dart \
  --objc_header_out ios/Runner/pigeon.h \
  --objc_source_out ios/Runner/pigeon.m \
  --experimental_swift_out ios/Runner/Pigeon.swift \
  --objc_header_out macos/Runner/pigeon.h \
  --objc_source_out macos/Runner/pigeon.m \
  --experimental_swift_out macos/Runner/Pigeon.swift \
  --java_out ./android/app/src/main/java/dev/flutter/pigeon/Pigeon.java \
  --java_out ./android/app/src/main/kotlin/com/rnd/flutter_ymodel/Pigeon.java \
  --java_package "com.rnd.flutter_ymodel"
