// Autogenerated from Pigeon (v3.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class YmodemRequest;
@class YmodemResponse;

@interface YmodemRequest : NSObject
+ (instancetype)makeWithCurrent:(nullable NSNumber *)current
    total:(nullable NSNumber *)total
    data:(nullable NSArray *)data
    msg:(nullable NSString *)msg;
@property(nonatomic, strong, nullable) NSNumber * current;
@property(nonatomic, strong, nullable) NSNumber * total;
@property(nonatomic, strong, nullable) NSArray * data;
@property(nonatomic, copy, nullable) NSString * msg;
@end

@interface YmodemResponse : NSObject
+ (instancetype)makeWithStatus:(nullable NSString *)status
    operate:(nullable NSString *)operate
    filename:(nullable NSString *)filename
    filepath:(nullable NSString *)filepath
    stop:(nullable NSNumber *)stop
    start:(nullable NSNumber *)start;
@property(nonatomic, copy, nullable) NSString * status;
@property(nonatomic, copy, nullable) NSString * operate;
@property(nonatomic, copy, nullable) NSString * filename;
@property(nonatomic, copy, nullable) NSString * filepath;
@property(nonatomic, strong, nullable) NSNumber * stop;
@property(nonatomic, strong, nullable) NSNumber * start;
@end

/// The codec used by YmodemRequestApi.
NSObject<FlutterMessageCodec> *YmodemRequestApiGetCodec(void);

@protocol YmodemRequestApi
/// @return `nil` only when `error != nil`.
- (nullable YmodemRequest *)getMessageParams:(YmodemResponse *)params error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void YmodemRequestApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YmodemRequestApi> *_Nullable api);

NS_ASSUME_NONNULL_END
